version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: mysql-reservas
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mis-reservas
      MYSQL_DATABASE: reservasDB
    ports:
      - 3308:3306
    volumes:
      - "./docker/mysql.cnf:/etc/mysql/conf.d/mysql.cnf"
      - "./docker/reservation_db.sql:/docker-entrypoint-initdb.d/1reservation_db"
      - "./docker/insertUsers.sql:/docker-entrypoint-initdb.d/2insertUsers.sql"
      - "./docker/insertBuildings.sql:/docker-entrypoint-initdb.d/3insertBuildings.sql"
      - "./docker/insertRooms.sql:/docker-entrypoint-initdb.d/4insertRooms.sql"
      - "./docker/insertResources.sql:/docker-entrypoint-initdb.d/5insertResources.sql"
      - "./docker/insertReservations.sql:/docker-entrypoint-initdb.d/6insertReservations.sql"
    networks:
      - reservas
  node:
    build: ./backend
    container_name: node-reservas
    restart: always 
    ports:
      - 3000:3000
    depends_on:
      - mysql
    networks:
      - reservas
    volumes:
      - ./backend:/usr/src/app
      - exclude:/usr/src/app/node_modules/
volumes:
  exclude:
networks:
  reservas:
